# Generated by Django 5.1.7 on 2025-03-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="birth",
            field=models.CharField(max_length=200),
        ),
    ]
