# Generated by Django 5.1.7 on 2025-04-01 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_chatmessage_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatmessage",
            options={"ordering": ["timestamp"]},
        ),
        migrations.RenameField(
            model_name="chatmessage",
            old_name="created_at",
            new_name="timestamp",
        ),
        migrations.RemoveField(
            model_name="chatsession",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="sender",
            field=models.CharField(
                choices=[("user", "Người dùng"), ("staff", "Nhân viên")],
                default="user",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="user_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="user_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="core.chatsession",
            ),
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="session_id",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
