# Generated by Django 5.0.2 on 2025-04-05 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_document_additional_requirements_alter_document_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="progress",
            field=models.IntegerField(default=0, help_text="Tiến trình xử lý (0-100%)"),
        ),
        migrations.AddField(
            model_name="document",
            name="progress_message",
            field=models.CharField(
                blank=True,
                help_text="Thông báo về tiến trình hiện tại",
                max_length=255,
                null=True,
            ),
        ),
    ]
