# Generated by Django 5.0.2 on 2025-04-05 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_document_progress_document_progress_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Tên môn học"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Mã môn học"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Mô tả"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Môn học",
                "verbose_name_plural": "Danh sách môn học",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="document",
            name="subject_text",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Tên môn học (cũ)"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="subject_text",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Tên môn học (cũ)"
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="subject",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="core.subject",
                verbose_name="Môn học",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="subject",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="core.subject",
                verbose_name="Môn học",
            ),
        ),
    ]
