# Generated by Django 5.0.2 on 2025-04-05 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_document_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="subject_text",
        ),
    ]
