# Generated by Django 5.1.7 on 2025-03-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sbd", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=200)),
                ("birth", models.DateField()),
                ("place", models.CharField(max_length=200)),
                ("sex", models.CharField(max_length=200)),
                ("class_name", models.CharField(max_length=200)),
                ("school", models.CharField(max_length=200)),
                ("subject", models.CharField(max_length=200)),
                ("score", models.FloatField()),
                ("rank", models.CharField(max_length=200)),
                ("prize", models.CharField(max_length=200)),
            ],
        ),
    ]
