# Generated by Django 5.1.7 on 2025-03-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_candidate_birth"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="exam_type",
            field=models.CharField(default="data1", max_length=50),
        ),
    ]
