# Generated by Django 5.1.7 on 2025-04-01 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_chatsession_chatmessage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatmessage",
            options={},
        ),
        migrations.RenameField(
            model_name="chatmessage",
            old_name="timestamp",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="chatmessage",
            name="is_read",
        ),
        migrations.RemoveField(
            model_name="chatmessage",
            name="sender",
        ),
        migrations.RemoveField(
            model_name="chatsession",
            name="user_email",
        ),
        migrations.RemoveField(
            model_name="chatsession",
            name="user_name",
        ),
        migrations.AddField(
            model_name="chatsession",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.chatsession"
            ),
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="session_id",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
