# Generated by Django 5.0.2 on 2025-04-04 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_informaticsexam_examattempt_informaticsquestion_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentanswer",
            name="attempt",
        ),
        migrations.RemoveField(
            model_name="questionimport",
            name="exam",
        ),
        migrations.RemoveField(
            model_name="informaticsquestion",
            name="exam",
        ),
        migrations.RemoveField(
            model_name="studentanswer",
            name="question",
        ),
        migrations.RemoveField(
            model_name="questionchoice",
            name="question",
        ),
        migrations.RemoveField(
            model_name="studentanswer",
            name="selected_choices",
        ),
        migrations.DeleteModel(
            name="ExamAttempt",
        ),
        migrations.DeleteModel(
            name="QuestionImport",
        ),
        migrations.DeleteModel(
            name="InformaticsExam",
        ),
        migrations.DeleteModel(
            name="InformaticsQuestion",
        ),
        migrations.DeleteModel(
            name="QuestionChoice",
        ),
        migrations.DeleteModel(
            name="StudentAnswer",
        ),
    ]
