# Generated by Django 5.0.2 on 2025-04-05 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_subject_document_subject_text_question_subject_text_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answer",
            options={
                "ordering": ["position"],
                "verbose_name": "Đáp án",
                "verbose_name_plural": "Danh sách đáp án",
            },
        ),
        migrations.AlterModelOptions(
            name="candidate",
            options={
                "ordering": ["name"],
                "verbose_name": "Thí sinh",
                "verbose_name_plural": "Danh sách thí sinh",
            },
        ),
        migrations.AlterModelOptions(
            name="document",
            options={
                "ordering": ["uploaded_at"],
                "verbose_name": "Tài liệu",
                "verbose_name_plural": "Danh sách tài liệu",
            },
        ),
        migrations.AlterModelOptions(
            name="question",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Câu hỏi",
                "verbose_name_plural": "Danh sách câu hỏi",
            },
        ),
        migrations.AlterModelOptions(
            name="uploadedfile",
            options={
                "ordering": ["uploaded_at"],
                "verbose_name": "Tệp upload",
                "verbose_name_plural": "Danh sách tệp upload",
            },
        ),
        migrations.CreateModel(
            name="ReferralCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Mã giới thiệu"
                    ),
                ),
                (
                    "remaining_uses",
                    models.PositiveIntegerField(
                        default=10, verbose_name="Số lần sử dụng còn lại"
                    ),
                ),
                (
                    "max_uses",
                    models.PositiveIntegerField(
                        default=10, verbose_name="Tổng số lần sử dụng tối đa"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Còn hiệu lực"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ngày hết hạn"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_referral_codes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người tạo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mã giới thiệu",
                "verbose_name_plural": "Danh sách mã giới thiệu",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "referral_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referred_users",
                        to="core.referralcode",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
