# Generated by Django 5.0.2 on 2025-04-05 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_alter_answer_options_alter_candidate_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Số điện thoại"
            ),
        ),
    ]
