# Generated by Django 5.0.2 on 2025-04-05 02:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_userprofile_phone"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ReferralCode",
            new_name="InviteCode",
        ),
        migrations.RenameField(
            model_name="userprofile",
            old_name="referral_code",
            new_name="invite_code",
        ),
    ]
