# Generated by Django 5.0.2 on 2025-04-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_rename_referralcode_invitecode_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invitecode",
            name="expires_at",
        ),
        migrations.RemoveField(
            model_name="invitecode",
            name="max_uses",
        ),
        migrations.AlterField(
            model_name="invitecode",
            name="remaining_uses",
            field=models.PositiveIntegerField(
                default=10, verbose_name="Số lần sử dụng"
            ),
        ),
    ]
