# Generated by Django 5.0.2 on 2025-04-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_remove_invitecode_expires_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answer",
            options={
                "ordering": ["position"],
                "verbose_name": "Đáp án",
                "verbose_name_plural": "Đáp án",
            },
        ),
        migrations.AlterModelOptions(
            name="candidate",
            options={
                "ordering": ["name"],
                "verbose_name": "Thí sinh",
                "verbose_name_plural": "Thí sinh",
            },
        ),
        migrations.AlterModelOptions(
            name="document",
            options={
                "ordering": ["uploaded_at"],
                "verbose_name": "Tài liệu",
                "verbose_name_plural": "Tài liệu",
            },
        ),
        migrations.AlterModelOptions(
            name="invitecode",
            options={
                "verbose_name": "Mã giới thiệu",
                "verbose_name_plural": "Mã giới thiệu",
            },
        ),
        migrations.AlterModelOptions(
            name="question",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Câu hỏi",
                "verbose_name_plural": "Câu hỏi",
            },
        ),
        migrations.AlterModelOptions(
            name="subject",
            options={
                "ordering": ["name"],
                "verbose_name": "Môn học",
                "verbose_name_plural": "Môn học",
            },
        ),
        migrations.AlterModelOptions(
            name="uploadedfile",
            options={
                "ordering": ["uploaded_at"],
                "verbose_name": "Tệp upload",
                "verbose_name_plural": "Tệp upload",
            },
        ),
        migrations.AddField(
            model_name="answer",
            name="explanation",
            field=models.TextField(
                blank=True, null=True, verbose_name="Giải thích đáp án"
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="is_correct",
            field=models.BooleanField(default=False, verbose_name="Là đáp án đúng"),
        ),
        migrations.AlterField(
            model_name="answer",
            name="text",
            field=models.TextField(verbose_name="Nội dung đáp án"),
        ),
    ]
